import { motion } from 'framer-motion'
import { ArrowUpRight, Recycle, Target, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import Button from '../components/common/Button'
import Container from '../components/common/Container'

const principles = [
  ['01', 'Useful work', 'We focus on the practical details that help recovered bottles move back into productive use.', Recycle],
  ['02', 'Clear quality', 'Cleaning, inspection and organized packing make each batch easier for a business to evaluate.', Target],
  ['03', 'Straightforward supply', 'We keep communication direct so buyers can discuss formats, quantities and timelines clearly.', Users],
]

export default function About() {
  return <main>
    <section className="grain relative isolate overflow-hidden border-b hairline pb-24 pt-40"><img src="/images/factory-yard.jpg" alt="JAY MAA KALI facility yard" className="absolute inset-0 z-0 h-full w-full object-cover opacity-30" /><div className="absolute inset-0 z-0 bg-[#06100b]/75" /><Container className="relative z-10"><p className="eyebrow mb-8 text-xs text-[#86efac]">About the work</p><h1 className="display display-lg max-w-5xl font-semibold">A practical route<br /><span className="text-[#86efac]">back to use.</span></h1><p className="mt-9 max-w-xl text-lg leading-8 text-slate-300">JAY MAA KALI organizes recovered material through collection, sorting, washing and careful storage.</p></Container></section>
    <section className="section-pad bg-[#f1f4ed] text-[#06100b]"><Container className="grid gap-12 md:grid-cols-[.8fr_1.2fr]"><p className="eyebrow text-[10px] text-[#159447]">01 / Who we are</p><div><h2 className="display text-4xl font-semibold md:text-6xl">Useful work, clearly done.</h2><p className="mt-8 max-w-2xl text-base leading-8 text-slate-600">We are building a dependable link between recovered glass and the businesses that can use it again. Our role is simple: collect, prepare and present reusable bottles with enough clarity for a real business decision.</p><div className="mt-10 grid gap-5 border-t border-[#06100b]/15 pt-5 sm:grid-cols-3"><div><p className="display text-3xl font-semibold">05</p><p className="mt-2 text-xs uppercase tracking-[.14em] text-slate-500">workflow stages</p></div><div><p className="display text-3xl font-semibold">B2B</p><p className="mt-2 text-xs uppercase tracking-[.14em] text-slate-500">supply focus</p></div><div><p className="display text-3xl font-semibold">1:1</p><p className="mt-2 text-xs uppercase tracking-[.14em] text-slate-500">clear contact</p></div></div></div></Container></section>
    <section className="section-pad"><Container><div className="mb-14 max-w-xl"><p className="eyebrow mb-5 text-[10px] text-[#86efac]">02 / What guides us</p><h2 className="display text-4xl font-semibold md:text-6xl">Recovery with a reason.</h2></div><div className="grid gap-px bg-[rgba(196,224,202,.14)] md:grid-cols-3">{principles.map(([number, title, description, Icon], index) => <motion.article initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .1 }} key={title} className="bg-[#06100b] p-7"><Icon className="mb-20 text-[#86efac]" size={24} strokeWidth={1.5} /><p className="eyebrow text-[10px] text-[#86efac]">{number}</p><h3 className="display mt-4 text-2xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-400">{description}</p></motion.article>)}</div></Container></section>
    <section className="section-pad border-y hairline"><Container className="grid items-center gap-12 md:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow mb-5 text-[10px] text-[#86efac]">03 / Inside the facility</p><h2 className="display text-4xl font-semibold md:text-6xl">The details make the difference.</h2><p className="mt-7 max-w-lg text-base leading-8 text-slate-300">A dependable operation is built from ordinary things done consistently: clear sorting areas, working wash tanks, reusable crates and a team that knows what the next stage needs.</p><Link to="/process" className="mt-8 inline-flex items-center gap-2 border-b border-[#86efac] pb-2 text-sm font-semibold text-[#86efac]">Walk through the process <ArrowUpRight size={16} /></Link></div><div className="grid gap-4 sm:grid-cols-2"><div className="aspect-[.9] overflow-hidden border hairline"><img src="/images/sorting-yard.jpg" alt="Sorted material at the facility" className="h-full w-full object-cover grayscale transition duration-700 hover:scale-105 hover:grayscale-0" /></div><div className="mt-8 aspect-[.9] overflow-hidden border hairline sm:mt-0"><img src="/images/wash-tanks.jpg" alt="Wash tanks at the facility" className="h-full w-full object-cover grayscale transition duration-700 hover:scale-105 hover:grayscale-0" /></div></div></Container></section>
    <section className="section-pad border-y hairline bg-[#0d1812]"><Container className="grid items-center gap-12 md:grid-cols-[1fr_.9fr] md:gap-12"><div><p className="eyebrow mb-5 text-[10px] text-[#86efac]">04 / Our role</p><h2 className="display text-4xl font-semibold md:text-6xl">We make the next step easier.</h2><p className="mt-7 max-w-lg text-lg leading-8 text-slate-300">From the collection yard to the washing line, we keep the work organized and make each stage easier to understand.</p><Button to="/contact" className="mt-8">Talk to our team</Button></div><div className="relative aspect-[4/5] overflow-hidden border hairline"><img src="/images/crate-storage.jpg" alt="Material stored in reusable crates" className="h-full w-full object-cover grayscale transition duration-700 hover:scale-105 hover:grayscale-0" /><div className="absolute inset-0 bg-[#06100b]/20" /></div></Container></section>
    <section className="bg-[#86efac] py-20 text-[#06100b]"><Container className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="eyebrow mb-5 text-[10px] opacity-60">Ready to explore</p><h2 className="display max-w-2xl text-5xl font-semibold leading-[.92] md:text-7xl">See what can be supplied.</h2></div><Link to="/bottles" className="inline-flex items-center gap-2 text-sm font-semibold">Browse bottle categories <ArrowUpRight size={17} /></Link></Container></section>
  </main>
}
