import { MoveUpRight, PackageCheck } from 'lucide-react'
import { motion } from 'framer-motion'
import { Link } from 'react-router-dom'
import Button from '../components/common/Button'
import Container from '../components/common/Container'

const categories = [
  ['01', 'Wine Bottles', 'Cleaned and prepared glass bottles for wineries, bottlers and beverage businesses.', '/images/wine-bottles.jpg'],
  ['02', 'Whisky Bottles', 'Prepared bottles for reuse by distilleries, craft spirits and premium product lines.', '/images/whisky-bottles.jpg'],
  ['03', 'Other Glass Bottles', 'Reusable glass formats handled with the same attention to cleaning, inspection and packing.', '/images/glass-bottles.jpg'],
]

export default function Bottles() {
  return <main>
    <section className="grain relative isolate overflow-hidden border-b hairline pb-24 pt-40"><img src="/images/wine-bottles.jpg" alt="Bottles arranged for supply" className="absolute inset-0 z-0 h-full w-full object-cover opacity-25" /><div className="absolute inset-0 z-0 bg-[#06100b]/80" /><Container className="relative z-10"><p className="eyebrow mb-8 text-xs text-[#86efac]">Bottle supply</p><h1 className="display display-lg max-w-5xl font-semibold">Glass prepared<br /><span className="text-[#86efac]">for what is next.</span></h1><p className="mt-9 max-w-xl text-lg leading-8 text-slate-300">A focused collection of bottle categories, handled through a clear preparation and packing workflow for business buyers.</p></Container></section>
    <section className="section-pad"><Container><div className="mb-14 flex items-end justify-between"><div><p className="eyebrow mb-5 text-[10px] text-[#86efac]">01 / Categories</p><h2 className="display text-4xl font-semibold md:text-6xl">Find the right material.</h2></div><PackageCheck className="hidden text-[#86efac] md:block" size={32} strokeWidth={1.2} /></div><div className="grid gap-5 md:grid-cols-3">{categories.map(([number, title, description, image], index) => <motion.article initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .1 }} whileHover={{ y: -6 }} key={title} className="surface group overflow-hidden"><div className="relative aspect-[1.15] overflow-hidden"><img src={image} alt={title} className="h-full w-full object-cover grayscale transition duration-700 group-hover:scale-105 group-hover:grayscale-0" /><div className="absolute inset-0 bg-[#06100b]/30" /></div><div className="p-6"><p className="eyebrow text-[10px] text-[#86efac]">{number}</p><h3 className="display mt-4 text-2xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{description}</p><Link to="/contact" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold">Make an enquiry <MoveUpRight size={15} className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></Link></div></motion.article>)}</div></Container></section>
    <section className="section-pad border-y hairline bg-[#f1f4ed] text-[#06100b]"><Container className="grid gap-10 md:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow mb-5 text-[10px] text-[#159447]">02 / Quality & preparation</p><h2 className="display text-4xl font-semibold md:text-6xl">Ready means ready to handle.</h2></div><div><p className="max-w-xl text-lg leading-8 text-slate-600">Cleaning, inspection and packing are part of the journey. We organize bottles into cartons so they can be discussed, transported and supplied with greater clarity.</p><ul className="mt-8 grid gap-3 text-sm text-slate-600 sm:grid-cols-2"><li>Batch-based handling</li><li>Visual quality checks</li><li>Careful carton packing</li><li>Business-first communication</li></ul></div></Container></section>
    <section className="section-pad"><Container className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="eyebrow mb-5 text-[10px] text-[#86efac]">03 / Need a format?</p><h2 className="display max-w-2xl text-4xl font-semibold md:text-6xl">Tell us what your next run needs.</h2></div><Button to="/contact">Discuss your requirement</Button></Container></section>
  </main>
}
