import { MoveUpRight, PackageCheck } from 'lucide-react'
import { motion } from 'framer-motion'
import { Link } from 'react-router-dom'
import Button from '../components/common/Button'
import Container from '../components/common/Container'

const categories = [
  ['01', 'Collection yard', 'Recovered material arrives at the facility before sorting and preparation.', '/images/factory-yard.jpg'],
  ['02', 'Sorting area', 'Collected material is separated and organized for the cleaning workflow.', '/images/sorting-yard.jpg'],
  ['03', 'Washing system', 'The wash line prepares material through a visible, sequential process.', '/images/wash-line.jpg'],
]
const facilityGallery = [
  ['Washing line', '/images/wash-line.jpg'],
  ['Wash tanks', '/images/wash-tanks.jpg'],
  ['Crate storage', '/images/crate-storage.jpg'],
]

export default function Bottles() {
  return <main>
    <section className="grain relative isolate overflow-hidden border-b hairline pb-24 pt-40"><img src="/images/factory-yard.jpg" alt="JAY MAA KALI collection yard" className="absolute inset-0 z-0 h-full w-full object-cover opacity-25" /><div className="absolute inset-0 z-0 bg-[#06100b]/80" /><Container className="relative z-10"><p className="eyebrow mb-8 text-xs text-[#86efac]">Facility and supply</p><h1 className="display display-lg max-w-5xl font-semibold">Material prepared<br /><span className="text-[#86efac]">for what is next.</span></h1><p className="mt-9 max-w-xl text-lg leading-8 text-slate-300">See how recovered material moves from collection and sorting through washing, storage and supply.</p></Container></section>
    <section className="section-pad"><Container><div className="mb-14 flex items-end justify-between"><div><p className="eyebrow mb-5 text-[10px] text-[#86efac]">01 / Categories</p><h2 className="display text-4xl font-semibold md:text-6xl">Find the right material.</h2></div><PackageCheck className="hidden text-[#86efac] md:block" size={32} strokeWidth={1.2} /></div><div className="grid gap-5 md:grid-cols-3">{categories.map(([number, title, description, image], index) => <motion.article initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .1 }} whileHover={{ y: -6 }} key={title} className="surface group overflow-hidden"><div className="relative aspect-[1.15] overflow-hidden"><img src={image} alt={title} className="h-full w-full object-cover grayscale transition duration-700 group-hover:scale-105 group-hover:grayscale-0" /><div className="absolute inset-0 bg-[#06100b]/30" /></div><div className="p-6"><p className="eyebrow text-[10px] text-[#86efac]">{number}</p><h3 className="display mt-4 text-2xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{description}</p><Link to="/contact" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold">Make an enquiry <MoveUpRight size={15} className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></Link></div></motion.article>)}</div></Container></section>
    <section className="section-pad border-y hairline bg-[#0d1812]"><Container><div className="mb-12 max-w-2xl"><p className="eyebrow mb-5 text-[10px] text-[#86efac]">02 / Inside the facility</p><h2 className="display text-4xl font-semibold md:text-6xl">The supply story, in pictures.</h2><p className="mt-6 text-base leading-8 text-slate-300">A closer look at the washing, holding and storage spaces that keep each stage organized.</p></div><div className="grid gap-5 md:grid-cols-[1.25fr_.75fr]">{facilityGallery.map(([title, image], index) => <div key={title} className={`group relative overflow-hidden border hairline ${index === 0 ? 'row-span-2 aspect-[1.1] md:aspect-auto' : 'aspect-[1.35]'}`}><img src={image} alt={title} className="h-full w-full object-cover grayscale transition duration-700 group-hover:scale-105 group-hover:grayscale-0" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#06100b] to-transparent px-5 pb-5 pt-14"><p className="display text-xl font-semibold">{title}</p></div></div>)}</div></Container></section>
    <section className="section-pad border-y hairline bg-[#f1f4ed] text-[#06100b]"><Container className="grid gap-10 md:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow mb-5 text-[10px] text-[#159447]">03 / Quality & preparation</p><h2 className="display text-4xl font-semibold md:text-6xl">Ready means ready to handle.</h2></div><div><p className="max-w-xl text-lg leading-8 text-slate-600">Cleaning, inspection and packing are part of the journey. We organize material into clear batches so it can be discussed, transported and supplied with greater clarity.</p><ul className="mt-8 grid gap-3 text-sm text-slate-600 sm:grid-cols-2"><li>Batch-based handling</li><li>Visible quality checks</li><li>Careful crate storage</li><li>Business-first communication</li></ul></div></Container></section>
    <section className="section-pad"><Container className="grid gap-10 md:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow mb-5 text-[10px] text-[#86efac]">04 / Buyer checklist</p><h2 className="display text-4xl font-semibold md:text-6xl">Bring us a clear requirement.</h2><p className="mt-6 max-w-sm text-base leading-7 text-slate-400">The fastest way to find a fit is to share a few practical details up front.</p></div><div className="grid gap-3 sm:grid-cols-2">{['Material or bottle type', 'Approximate quantity', 'Preferred timeline', 'Delivery or pickup needs'].map((item, index) => <div key={item} className="surface flex items-center gap-4 p-5"><span className="eyebrow text-[10px] text-[#86efac]">0{index + 1}</span><span className="text-sm text-slate-200">{item}</span></div>)}</div></Container></section>
    <section className="section-pad"><Container className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="eyebrow mb-5 text-[10px] text-[#86efac]">03 / Need a format?</p><h2 className="display max-w-2xl text-4xl font-semibold md:text-6xl">Tell us what your next run needs.</h2></div><Button to="/contact">Discuss your requirement</Button></Container></section>
  </main>
}
