import { ArrowUpRight, Mail, MapPin, Phone, ShieldCheck } from 'lucide-react'
import { motion } from 'framer-motion'
import Container from '../components/common/Container'

const contactDetails = [
  [Phone, '[Phone Number]', 'Call for a quick supply conversation.', 'tel:+910000000000'],
  [Mail, '[Email Address]', 'Share formats, quantities or a brief.', 'mailto:hello@example.com'],
  [MapPin, '[Business Address]', 'Serving business requirements from Chhattisgarh.', '#'],
]

export default function Contact() {
  return <main>
    <section className="grain relative overflow-hidden border-b hairline pb-24 pt-40"><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1600&q=85" alt="Business team discussing supply" className="absolute inset-0 -z-10 h-full w-full object-cover opacity-20" /><div className="absolute inset-0 -z-10 bg-[#06100b]/85" /><Container><motion.p initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} className="eyebrow mb-8 text-xs text-[#86efac]">Business enquiries</motion.p><motion.h1 initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .08 }} className="display display-lg max-w-5xl font-semibold">Let us make the<br /><span className="text-[#86efac]">next move practical.</span></motion.h1><motion.p initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .16 }} className="mt-9 max-w-xl text-lg leading-8 text-slate-300">Tell us what you are looking for and we will make space for a useful conversation about reusable glass supply.</motion.p></Container></section>
    <section className="section-pad"><Container className="grid gap-16 md:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow mb-7 text-[10px] text-[#86efac]">01 / Contact information</p><div className="grid gap-3">{contactDetails.map(([Icon, text, description, href], index) => <motion.a initial={{ opacity: 0, x: -14 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: index * .1 }} href={href} className="group flex items-start gap-4 border-b hairline py-5 transition-colors hover:border-[#86efac]" key={text}><Icon size={19} className="mt-1 text-[#86efac]" /><div><p className="leading-6 text-slate-200 group-hover:text-[#86efac]">{text}</p><p className="mt-1 text-xs leading-5 text-slate-500">{description}</p></div><ArrowUpRight size={15} className="ml-auto text-slate-600 transition group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-[#86efac]" /></motion.a>)}</div><div className="mt-10 border-t hairline pt-6"><p className="eyebrow text-[10px] text-slate-500">For bottle formats, quantities, sourcing and supply requirements.</p></div></div><motion.div initial={{ opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="surface relative overflow-hidden p-7 md:p-12"><div className="absolute -right-16 -top-16 h-48 w-48 rounded-full border border-[#86efac]/20" /><ShieldCheck className="mb-20 text-[#86efac]" size={28} strokeWidth={1.4} /><p className="eyebrow mb-5 text-[10px] text-[#86efac]">02 / A simple next step</p><h2 className="display max-w-lg text-4xl font-semibold md:text-6xl">Bring us the requirement.</h2><p className="mt-6 max-w-md text-base leading-8 text-slate-400">Call or email with the bottle type, approximate quantity and timeline you have in mind. We will help you understand the most practical route forward.</p><a href="mailto:hello@example.com" className="group mt-9 inline-flex items-center gap-3 border-b border-[#86efac] pb-2 text-sm font-semibold text-[#86efac]">Start an email <ArrowUpRight size={17} className="transition group-hover:-translate-y-1 group-hover:translate-x-1" /></a></motion.div></Container></section>
    <section className="section-pad border-t hairline bg-[#f1f4ed] text-[#06100b]"><Container className="grid gap-10 md:grid-cols-2"><div><p className="eyebrow mb-5 text-[10px] text-[#159447]">03 / What happens next</p><h2 className="display text-4xl font-semibold md:text-6xl">A useful reply, not a maze.</h2></div><div className="grid gap-4 text-sm text-slate-600"><p className="border-b border-[#06100b]/15 pb-4">01. We review your requirement.</p><p className="border-b border-[#06100b]/15 pb-4">02. We discuss available formats and quantities.</p><p className="border-b border-[#06100b]/15 pb-4">03. We outline the most practical next step.</p></div></Container></section>
  </main>
}
