import { motion } from 'framer-motion'
import { ArrowDown, Check, ClipboardCheck, Package, Sparkles, Truck } from 'lucide-react'
import Button from '../components/common/Button'
import Container from '../components/common/Container'

const steps = [
  ['01', 'Collection', 'Used and empty wine, whisky and other glass bottles are gathered for the next stage.', Truck],
  ['02', 'Cleaning', 'Bottles are cleaned and prepared for a closer look.', Sparkles],
  ['03', 'Inspection', 'Each batch moves through an inspection and quality check.', ClipboardCheck],
  ['04', 'Packing', 'Prepared bottles are organized into cartons for careful handling.', Package],
  ['05', 'Supply', 'Ready material is supplied to distilleries and business customers.', Check],
]

export default function Process() {
  return <main>
    <section className="grain relative isolate overflow-hidden border-b hairline pb-24 pt-40"><img src="/images/whisky-bottles.jpg" alt="Glass bottles being handled" className="absolute inset-0 z-0 h-full w-full object-cover opacity-25" /><div className="absolute inset-0 z-0 bg-[#06100b]/80" /><Container className="relative z-10"><p className="eyebrow mb-8 text-xs text-[#86efac]">Our process</p><h1 className="display display-lg max-w-5xl font-semibold">From empty bottle<br /><span className="text-[#86efac]">to ready supply.</span></h1><p className="mt-9 max-w-xl text-lg leading-8 text-slate-300">A visible, sequential workflow designed around care, preparation and business-ready handling.</p></Container></section>
    <section className="section-pad"><Container><div className="mb-16 flex items-end justify-between"><div><p className="eyebrow mb-5 text-[10px] text-[#86efac]">01 / The workflow</p><h2 className="display text-4xl font-semibold md:text-6xl">Five considered steps.</h2></div><ArrowDown className="hidden text-[#86efac] md:block" /></div><div className="relative ml-3 border-l border-[#86efac]/40 md:ml-0 md:border-l-0">{steps.map(([number, title, description, Icon], index) => <motion.article initial={{ opacity: 0, x: 20 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, margin: '-80px' }} transition={{ delay: index * .06 }} key={number} className="relative grid gap-x-6 gap-y-3 border-b hairline py-8 pl-8 md:grid-cols-[56px_minmax(0,1fr)_32px] md:items-start md:py-10 md:pl-0 lg:grid-cols-[56px_minmax(220px,300px)_minmax(0,1fr)_40px]"><span className="absolute -left-[7px] top-10 h-3 w-3 rounded-full bg-[#86efac] shadow-[0_0_18px_#86efac] md:static md:mt-2 md:h-2 md:w-2" /><span className="eyebrow text-[11px] text-[#86efac]">{number}</span><h3 className="display text-2xl font-semibold md:col-start-2 md:row-start-1 md:text-3xl lg:col-start-2">{title}</h3><p className="max-w-prose text-sm leading-7 text-slate-400 md:col-start-2 md:row-start-2 md:text-base lg:col-start-3 lg:row-start-1">{description}</p><Icon className="hidden text-[#86efac] md:col-start-3 md:row-start-1 md:block lg:col-start-4" size={20} strokeWidth={1.5} /></motion.article>)}</div></Container></section>
    <section className="section-pad border-y hairline bg-[#0d1812]"><Container className="grid items-center gap-10 md:grid-cols-[minmax(0,1fr)_minmax(280px,.9fr)] md:gap-12"><div><p className="eyebrow mb-5 text-[10px] text-[#86efac]">02 / Quality focus</p><h2 className="display text-4xl font-semibold md:text-6xl">Preparation you can follow.</h2><p className="mt-7 max-w-lg text-base leading-8 text-slate-300 md:text-lg">A clear sequence gives buyers a better view of what is happening before supply is discussed. It also gives every bottle a more considered chance at another useful cycle.</p></div><div className="relative aspect-[4/3] min-h-[240px] overflow-hidden border hairline"><img src="/images/whisky-bottles.jpg" alt="Whisky bottles prepared for reuse" className="h-full w-full object-cover grayscale transition duration-700 hover:scale-105 hover:grayscale-0" /></div></Container></section>
    <section className="bg-[#86efac] py-20 text-[#06100b]"><Container className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><h2 className="display max-w-2xl text-5xl font-semibold leading-[.92] md:text-7xl">Good supply starts with a clear process.</h2><Button to="/contact" variant="outline" className="w-fit border-[#06100b] text-[#06100b] hover:bg-[#06100b] hover:text-[#86efac]">Start a conversation</Button></Container></section>
  </main>
}
